### ISSUE TITLE
Check session cookie when sending multiple calls

### ISSUE THREAD

**Issue by munichrocker** [munichrocker/DatawRappr#31]
Datawrapper uses session cookies, if there's an unauthenticated call to v1. This package uses v3 and authenticated calls, but there have been reports of 401 errors on Windows when using dw_edit_chart() multiple times in a single R session.

This needs to be investigated. A possible solution might be to add a handle = '' to the httr call

**Comment by munichrocker** [comment]
Should be fixed in https://github.com/munichrocker/DatawRappr/commit/8d17ab99e2f04085b6ee804827f081c9380cdb7c

**Comment by fin** [comment]
I just (still, after this fix) had this issue both on OSX and on Ubuntu.

Addinghttr::handle_reset("https://api.datawrapper.de/") in front of the 2nd dw_edit_chart call helped.
I think the issues is that I'm doing multiple things in this order

dw_data_to_chart
dw_edit_chart
dw_publish_chart
and dw_edit_chart also suffers from side-effects from other calls?

**Comment by munichrocker** [comment]
Yes, **Adding** `httr::handle_reset("https://api.datawrapper.de/")` after the first (or before the second dw_edit_chart-call is the only known workaround right now. 

https://github.com/munichrocker/DatawRappr/commit/ac205dcde0eebe6077e5df6431896dfff50502aa should've fixed it. But it doesn't.

dw_data_to_chart and dw_publish_chart both use different APIs. It could be a side effect, but I'm not sure.

Needs further investigation. I see it's a huge problem right now with Corona. Try to get it done this week.

**Comment by fin** [comment]
I decided to look into this a bit more. One more thing that breaks is `dw_list_charts`, which returns an empty result. a quick search through the codebase for api.datawrapper.de returns only `/v3/` results - except `dw_publish_chart`. so that might be the culprit.

i could reproduce the issue by creating charts using a different user, then editing them with my auth key. adding `httr::handle_reset` to `dw_publish_chart` fixed the issue.

pull request incoming
